version: "3.9"  # optional since v1.27.0
services:
  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_DB_CONNECTION_STRING=mongodb+srv://MartSorensen:sqCeq6XPUpPAzB1t@cluster0.gyurfl9.mongodb.net/test
      - MONGO_DB_NAME=cluster0
      - REDIS_URI=rediss://default:AVNS_xuvwWMetqfXcEdOqFyW@redis-2222805b-harsvamp1234-fd3e.aivencloud.com:23636
      